force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Storing all the information about the employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <description>Employee Unique Identification</description>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tags Employees to a Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Object to store data of the Projects in the Company</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Policy__c/Project_Policy__c.object-meta.xml
<CustomObject>
    <description>Policies for any given Project</description>
    <label>Project Policy</label>
    <nameField>
        <label>Project Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Policies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Policy__c/fields/Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Number__c</fullName>
    <description>Unique Policy Number for each Policy</description>
    <displayFormat>P-{00}</displayFormat>
    <label>Policy Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Project_Policy__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Policies of The Project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Policies</relationshipLabel>
    <relationshipName>Project_Policies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of each Policy enactment</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Not Applied</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PolicySearch.cls
public with sharing class PolicySearch
{
@AuraEnabled(cacheable=true)
 public static list<SObject> getPolicyList(String searchKey){
 string searchKeyword = '%' + searchKey + '%';
 
     string projectname = '';
        
        list<Employee__c> employeeproj = new list<Employee__c>();
        list<SObject> projpolicy = new list<SObject>();
        
        employeeproj = [Select id,Project__r.Name From Employee__c WHERE Employee_ID__c LIKE : searchKeyword];
        
        projectname = employeeproj.get(0).Project__r.Name;
        
         for(Project_Policy__c polObj : [Select id, Project__r.Name,Name, Policy_Number__c, Status__c from Project_Policy__c where Project__r.Name =:projectname]){
           projpolicy.add(polObj);
        }
        
         if(projpolicy.size() == 0){
            throw new AuraHandledException('No Record Found..'); 
         }
        return projpolicy;
        
        }
        }