force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Storing all the information about the employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Employee Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Employee_ID__c</fullName>
    <description>Employee Unique Identification</description>
    <label>Employee ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Months_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Months_of_Experience__c</fullName>
    <description>Employee Months of Job Experience</description>
    <label>Months of Experience</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Employee Phone Number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Primary_Skill__c.field-meta.xml
<CustomField>
    <fullName>Primary_Skill__c</fullName>
    <description>Employee Primary Skill</description>
    <label>Primary Skill</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>Scala</fullName>
            </value>
            <value>
                <fullName>Machine Learning</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Secondary_Skill__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Skill__c</fullName>
    <label>Secondary Skill</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
            <value>
                <fullName>Scala</fullName>
            </value>
            <value>
                <fullName>Machine Learning</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Supervisor of the given employee</description>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/customSearchEmployeeLWC.cls
/*
Description : Class to find the Employee(s) corresponding to the Employee Id, entered by the user in the Search Box of the Employee Tab*/

public with sharing class customSearchEmployeeLWC {
@AuraEnabled(cacheable=true)
    public static list<Employee__c> getEmployeeList(string searchKey) {
        string searchKeyword = '%' + searchKey + '%';
        
       
        list<Employee__c> employeeListRecord = new list<Employee__c>();
     

     //Searching for the all the employees with the similar sequence of Employee ID or The exact Employee
       
        for(Employee__c empObj : [Select id,Name,Employee_ID__c,Months_of_Experience__c,Primary_Skill__c,Secondary_Skill__c,Supervisor__c,Phone__c,Email__c
From Employee__c WHERE Employee_ID__c LIKE : searchKeyword]){
           employeeListRecord.add(empObj);
        }
        
         if(employeeListRecord.size() == 0){
            throw new AuraHandledException('No Record Found..'); 
         }
         
        return employeeListRecord; // returing the list of employee(s) back to the LWC, so it can be displayed in the Employee Tab
    }
}